# Use OpenJDK base image
FROM openjdk:11-jdk-slim

# Set working directory
WORKDIR /app

# Copy JAR from target to container
COPY target/demo-0.0.1-SNAPSHOT.jar app.jar

# Expose port
EXPOSE 8080

# Run the JAR
ENTRYPOINT ["java", "-jar", "app.jar"]
